
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER NUMBER DIGIT_CONSTANT STRING_CONSTANT ASSIGN ADDRESS LT GT SELF_PLUS SELF_MINUS PLUS MINUS MUL DIV GTE LTE LL_BRACKET RL_BRACKET LB_BRACKET RB_BRACKET LM_BRACKET RM_BRACKET COMMA DOUBLE_QUOTE SEMICOLON SHARP INCLUDE INT FLOAT CHAR DOUBLE FOR IF ELSE WHILE DO RETURNfile : empty\n            | file vardefine SEMICOLONvardefine : type defineListdefineList : defineElemdefineElem : IDENTIFIERtype : INTempty : '
    
_lr_action_items = {'INT':([0,1,2,6,],[-7,5,-1,-2,]),'$end':([0,1,2,6,],[-7,0,-1,-2,]),'SEMICOLON':([3,7,8,9,],[6,-3,-4,-5,]),'IDENTIFIER':([4,5,],[9,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'file':([0,],[1,]),'empty':([0,],[2,]),'vardefine':([1,],[3,]),'type':([1,],[4,]),'defineList':([4,],[7,]),'defineElem':([4,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('file -> empty','file',1,'p_file','parser.py',136),
  ('file -> file vardefine SEMICOLON','file',3,'p_file','parser.py',137),
  ('vardefine -> type defineList','vardefine',2,'p_vardefine','parser.py',140),
  ('defineList -> defineElem','defineList',1,'p_defineList','parser.py',144),
  ('defineElem -> IDENTIFIER','defineElem',1,'p_defineElem','parser.py',148),
  ('type -> INT','type',1,'p_type','parser.py',161),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',164),
]
